#!/bin/bash

declare -a ARGS=(-c opt --copt=-fPIC --config oss_linux unix/fcitx5:fcitx5-mozc.so server:mozc_server gui/tool:mozc_tool)
if [ -n "$PREFIX" ]; then
  ARGS+=(--linkopt=-L"$PREFIX"/lib)
fi
bazel build "${ARGS[@]}"
